[package]
name = "pivot"
version = "0.1.0"
edition = "2024"

[dependencies]
nix = { version = "0.27.1", features = ["mount", "fs", "signal", "process"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
libc = "0.2"
loopdev = { package = "loopdev-3", version = "0.5.3" }
fbppid-rs = { git = "https://github.com/FinchBerryOS/fbppid-rs.git" }